### ISSUE TITLE
Keyboard navigation doesn't appear to work

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/paper-tabs#27] opened 2015-06-04 19:41 UTC
Testing in the demo: https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html

It appears that I can move focus with the left/right keys. If I press Enter, I get a paper-ripple suggesting the item's been activated, but the selection bar doesn't move. It looks like the actual selection sin't changing.

**Comment by cdata** [comment] 2015-06-04 20:32
Closing as a dupe of #28 - re-open if that's an error!

**Closed by cdata** 2015-06-04 20:32 UTC
