### ISSUE TITLE
Setting the opacity of the scroll arrows and display dynamically depending on the use case

### ISSUE THREAD

**Issue by RonMen** [PolymerElements/paper-tabs#170] opened 2016-06-05 11:36 UTC
Hi there,

in issue #16 there is a fix to set visibility of  the arrows to hidden if not "needed", but I think it doesn't make sence to only set opacity to 0. I would suggest to also hide them completely to free up the space. Think of a dynamically usage where in some cases we may have 2-3 tabs or we can have 20 tabs, so depending on the needs it should shown or hide the buttons.

On the other hand the opacity shouldn't really be set to 0 since the user may wonder about the space when you eg. use the paper-tabs within the second/bottom app-toolbar of your header and the space on the left seems to be an issue then...

See the sample image below that shows what I'm thinking of:

![20160605_paper-tabs](https://cloud.githubusercontent.com/assets/2003172/15805158/8900e552-2b21-11e6-9c94-0e8a133ae772.jpg)

Regards
RonMen

**Comment by bicknellr** [comment] 2016-06-08 18:29
I'm going to close this as a dupe of #166. I agree that just doing either of `display: none;` or `opacity: 0;` won't be sufficient here, but I think absolutely positioning the arrows above the tabs might make this work. (There will need to be some changes to the 'scroll to show this item' function though.)

**Closed by bicknellr** 2016-06-08 18:29 UTC
