### ISSUE TITLE
Keyboard navigation doesn't appear to work

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/paper-tabs#28] opened 2015-06-04 19:43 UTC
Testing in the demo: https://elements.polymer-project.org/elements/paper-tabs?view=demo:demo/index.html

It appears that I can move focus with the left/right keys. If I press Enter, I get a paper-ripple suggesting the item's been activated, but the selection bar doesn't move. It looks like the actual selection isn't changing.

**Comment by cdata** [comment] 2015-06-04 20:32
Thanks for reporting @arthurevans, I can confirm this is a bug.

**Comment by morethanreal** [comment] 2015-06-04 22:46
The bug was introduced in https://github.com/PolymerElements/iron-selector/commit/77c2ed6bc8c88d6bd12a57f800bd0600d2d49896. It checks for the activate event, which is a keyboard event when it's focused with the keyboard. It seems like since there are multiple events that can trigger activation that code is incorrect.

**Comment by tjsavage** [comment] 2015-08-25 23:53
Closed via https://github.com/PolymerElements/paper-tabs/pull/52

**Closed by tjsavage** 2015-08-25 23:53 UTC
Labels: bug
